apiVersion : apps/v1
kind: Deployment
metadata:
  name: "avibcluster-47cf"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "avibcluster-47cf"
  template:
    metadata:
      labels:
        app: "avibcluster-47cf"
    spec:
      containers:
        - name: "avibcluster-47cf"
          image: "avibcontainerregistry.azurecr.io/avibcluster47cf"
          ports:
          - containerPort: 80